#!/usr/bin/env bash
# Assemble the CNisaba C target of packages/swift from the repository.
#
# Lives BESIDE the package, not in it, exactly like nisaba-db.build.mjs:
# the package directory holds only what ships, and nothing under
# packages/swift/Sources/CNisaba is a source of truth -- every file is
# copied from the repo at assemble time, so the Swift package can never
# drift from what the repository builds and tests.
#
# The source list is build/build-common.sh's `all_sources native` -- the
# SAME list build/build-native.sh compiles and CI runs under ASan/UBSan --
# plus server/root.c, the POSIX dbi_root implementation the native test
# harness links for the same reason we do: it is the one real
# openat/readdir/unlinkat implementation of db_instance.h's directory
# seam. Headers are flattened into one include/ directory (their names
# are globally unique; the builds have always compiled with every
# include dir on the path at once).
#
# Run it once after cloning (and again after pulling changes to the C):
#
#   ./packages/swift.build.sh
#
# `swift build` in packages/swift then works offline from the copies.
set -euo pipefail

cd "$(dirname "$0")/.."
. build/build-common.sh
require_submodules

PKG=packages/swift/Sources/CNisaba

rm -rf "$PKG"
mkdir -p "$PKG/src" "$PKG/include"

while IFS= read -r src; do
  cp "$src" "$PKG/src/"
done < <(all_sources native)

# The instance's directory seam (db_instance.h's dbi_root), POSIX flavor.
cp server/root.c "$PKG/src/"

# Private header the regex engine's sources share among themselves.
cp third_party/regex-engine/src/re_internal.h "$PKG/src/"

cp engine/include/*.h \
   third_party/binjson/include/*.h \
   third_party/binjson-structures/include/*.h \
   third_party/regex-engine/include/*.h \
   server/root.h \
   "$PKG/include/"

# The module Swift imports: an explicit umbrella of the embedding
# surface, not the whole include directory -- the deep headers stay
# reachable to the C sources without being compiled into the module.
cat > "$PKG/include/CNisaba.h" <<'EOF'
/* Generated by packages/swift.build.sh -- do not edit. The C surface the
 * Swift wrapper drives: binjson in and out, an instance over a POSIX
 * root directory, and the request handler. */
#ifndef CNISABA_H
#define CNISABA_H
#include "binjson.h"
#include "dbuf.h"
#include "bjio.h"
#include "bjns.h"
#include "bjio_posix.h"
#include "db_names.h"
#include "db_validate.h"
#include "db.h"
#include "db_session.h"
#include "db_instance.h"
#include "root.h"
#endif
EOF

cat > "$PKG/include/module.modulemap" <<'EOF'
module CNisaba {
    umbrella header "CNisaba.h"
    export *
}
EOF

count=$(ls "$PKG/src" | wc -l | tr -d ' ')
echo "assembled $count sources into $PKG"
